workflows:
  build-android:
    name: Build Android APK
    environment:
      vars:
        CAPACITOR_ANDROID_STUDIO_PATH: /opt/android-studio
      node: 18.18.2
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Ensure Android platform exists
        script: |
          chmod +x android/gradlew
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
