workflows:
  build-android:
    name: Build Android APK
    environment:
      node: 18.18.2
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Ensure Android platform exists
        script: |
          echo "Fixing permissions and syncing Android platform"
          chmod +x android/gradlew || true
          npx --yes cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
