workflows:
  site_search_app:
    name: Site Search Android Build
    max_build_duration: 15
    environment:
      vars:
        PACKAGE_NAME: "com.proconect.sitesearch"
      node: 18.16.0
    scripts:
      - name: Install Node dependencies
        script: |
          npm install
      - name: Add and Sync Android Platform
        script: |
          npm install @capacitor/android
          npx cap add android || true
          npx cap copy
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
