workflows:
  android-build:
    name: Android Build
    environment:
      node: 20.11.1
      npm: 10.2.4
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm install -D typescript
      - name: Ensure Android platform exists
        script: |
          npx cap sync android
      - name: Build web assets
        script: |
          npm run build
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
