workflows:
  build-android:
    name: Build Android APK
    environment:
      node: 18.18.2
      npm: 9.8.1
      android: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Ensure Android platform exists
        script: |
          chmod +x android/gradlew
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
