workflows:
  build-android:
    name: Build Android APK
    environment:
      node: 20.11.1  # ✅ Use Node >= 20 for Capacitor 7
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g @capacitor/cli
      - name: Ensure Android platform exists
        script: |
          echo "Fixing permissions and syncing Android platform"
          chmod +x android/gradlew || true
          capacitor sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
